[package]
name = "mediaplayer-control"
version = "0.1.2"
authors = ["Nikola Kocić <nikolakocic@gmail.com>"]
edition = "2018"

[dependencies]
dbus = "0.7"
chrono = "0.4"
clap = "2.33"
floating-duration = "0.1"
